#!/usr/bin/env python
# encoding: utf-8

name = "cathub_W"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 0,
    label = "X + X + N2 <=> NX + NX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(-0.824935,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246NDMzMDUz""",
    longDesc = 
"""
equation : N2(g) + 2.0* -> 2.0N*
dft_code : Quantum Espresso
dftFunctional : BEEF-vdW
pubId: WangAchieving2021
reactionEnergy: -4.322079935518559 eV
A determined such that the sticking coeff is >= .1 at 3000K
""",
    metal = "W",
    facet = "211",
)

entry(
    index = 1,
    label = "HX + NX <=> X + NHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.50073e+16,'m^2/(mol*s)','*|/',100), n=0, Ea=(2.26905,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246NDMzMDU0""",
    longDesc = 
"""
equation : H* + N* - 0* -> NH* + *
dft_code : Quantum Espresso
dftFunctional : BEEF-vdW
pubId: WangAchieving2021
reactionEnergy: 0.42867394210770726 eV

A factor estimation = kb*298/h/10 s^-1 / 2.483e-05 mol/m^2 (surface site density for Pt111)
""",
    metal = "W",
    facet = "211",
)

entry(
    index = 2,
    label = "HX + NHX <=> X + NH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.50073e+16,'m^2/(mol*s)','*|/',100), n=0, Ea=(1.74919,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246NDMzMDU1""",
    longDesc = 
"""
equation : NH* + H* - 0* -> NH2* + *
dft_code : Quantum Espresso
dftFunctional : BEEF-vdW
pubId: WangAchieving2021
reactionEnergy: 0.6058041401265655 eV

A factor estimation = kb*298/h/10 s^-1 / 2.483e-05 mol/m^2 (surface site density for Pt111)
""",
    metal = "W",
    facet = "211",
)

entry(
    index = 3,
    label = "HX + NH2X <=> X + NH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.50073e+16,'m^2/(mol*s)','*|/',100), n=0, Ea=(2.1428,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246NDMzMDU2""",
    longDesc = 
"""
equation : NH2* + H* - 0* -> NH3* + *
dft_code : Quantum Espresso
dftFunctional : BEEF-vdW
pubId: WangAchieving2021
reactionEnergy: 1.0558742582506966 eV

A factor estimation = kb*298/h/10 s^-1 / 2.483e-05 mol/m^2 (surface site density for Pt111)
""",
    metal = "W",
    facet = "211",
)

