#!/usr/bin/env python
# encoding: utf-8

name = "cathub_Fe"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 0,
    label = "H2OX + X <=> HX + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.50073e+16,'m^2/(mol*s)','*|/',100), n=0, Ea=(0.743,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246MTM4NQ==""",
    longDesc = 
"""
equation : H2O* -> OH* + H*
dft_code : DACAPO
dftFunctional : RPBE
pubId: WangUniversal2011
reactionEnergy: -0.601 eV

A factor estimation = kb*298/h/10 s^-1 / 2.483e-05 mol/m^2 (surface site density for Pt111)
""",
    metal = "Fe",
    facet = "111",
)

entry(
    index = 1,
    label = "COX + X <=> CX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.50073e+16,'m^2/(mol*s)','*|/',100), n=0, Ea=(1.09,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246MTI4NA==""",
    longDesc = 
"""
equation : CO* -> C* + O*
dft_code : DACAPO
dftFunctional : RPBE
pubId: WangUniversal2011
reactionEnergy: -0.83 eV

A factor estimation = kb*298/h/10 s^-1 / 2.483e-05 mol/m^2 (surface site density for Pt111)
""",
    metal = "Fe",
    facet = "211",
)

entry(
    index = 2,
    label = "OHX + X <=> HX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.50073e+16,'m^2/(mol*s)','*|/',100), n=0, Ea=(0.769,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246MTAwNQ==""",
    longDesc = 
"""
equation : OH* -> H* + O*
dft_code : DACAPO
dftFunctional : RPBE
pubId: WangUniversal2011
reactionEnergy: -0.206 eV

A factor estimation = kb*298/h/10 s^-1 / 2.483e-05 mol/m^2 (surface site density for Pt111)
""",
    metal = "Fe",
    facet = "211",
)

entry(
    index = 3,
    label = "CO + X + X <=> CX + OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(-0.437,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246MTIyNg==""",
    longDesc = 
"""
equation : CO(g) -> C* + O*
dft_code : DACAPO
dftFunctional : RPBE
pubId: WangUniversal2011
reactionEnergy: -2.357 eV
A determined such that the sticking coeff is >= .1 at 3000K
""",
    metal = "Fe",
    facet = "211",
)

entry(
    index = 4,
    label = "H2O + X + X <=> HX + OHX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1.2406, n=0, Ea=(0.651,'eV/molecule'), T0=(1,'K')),
    shortDesc = """cathub_id:UmVhY3Rpb246MTM3OA==""",
    longDesc = 
"""
equation : H2O(g) -> OH* + H*
dft_code : DACAPO
dftFunctional : RPBE
pubId: WangUniversal2011
reactionEnergy: -0.693 eV
A determined such that the sticking coeff is >= .1 at 3000K
""",
    metal = "Fe",
    facet = "111",
)

